name: test_allerhands
description: A test flutter project for allerhands

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: any
  readmore: ^2.2.0
  auto_route: ^5.0.4
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.1
  auto_size_text: ^3.0.0
  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  auto_route_generator: any

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile_pics/
    - assets/icons/
    - assets/icons/room_icons/
    - assets/videos/
    - assets/fonts/
    - assets/videos/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/playfair_display/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/playfair_display/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/playfair_display/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/playfair_display/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
